import React from 'react'

const StickyDemo = () => {
    return (
        <div className='flex gap-1 p-1  w-full'>

            <p className='sticky top-0 bg-black p-2 text-white'>Hello</p>
            <div className='flex flex-col gap-1 h-44 overflow-y-scroll example'>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio tenetur officia placeat cupiditate saepe iusto deserunt, temporibus sequi iure quidem molestiae modi voluptate quae magnam ab sapiente doloribus ex laudantium expedita voluptas excepturi et corrupti id. Deserunt inventore reprehenderit est debitis distinctio. Tempora vitae quibusdam eius! Sunt laborum, deserunt laboriosam rem, eligendi libero dignissimos officia saepe ut nostrum illum soluta, inventore cum. Accusamus deleniti aliquam, provident expedita corporis quos minus dolorum aspernatur distinctio at non amet fugit enim. Maxime cupiditate voluptate inventore nam sed sunt iusto? Excepturi nostrum sapiente, consequuntur alias delectus, expedita ea quaerat rerum, enim eius libero ipsam?</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio tenetur officia placeat cupiditate saepe iusto deserunt, temporibus sequi iure quidem molestiae modi voluptate quae magnam ab sapiente doloribus ex laudantium expedita voluptas excepturi et corrupti id. Deserunt inventore reprehenderit est debitis distinctio. Tempora vitae quibusdam eius! Sunt laborum, deserunt laboriosam rem, eligendi libero dignissimos officia saepe ut nostrum illum soluta, inventore cum. Accusamus deleniti aliquam, provident expedita corporis quos minus dolorum aspernatur distinctio at non amet fugit enim. Maxime cupiditate voluptate inventore nam sed sunt iusto? Excepturi nostrum sapiente, consequuntur alias delectus, expedita ea quaerat rerum, enim eius libero ipsam?</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio tenetur officia placeat cupiditate saepe iusto deserunt, temporibus sequi iure quidem molestiae modi voluptate quae magnam ab sapiente doloribus ex laudantium expedita voluptas excepturi et corrupti id. Deserunt inventore reprehenderit est debitis distinctio. Tempora vitae quibusdam eius! Sunt laborum, deserunt laboriosam rem, eligendi libero dignissimos officia saepe ut nostrum illum soluta, inventore cum. Accusamus deleniti aliquam, provident expedita corporis quos minus dolorum aspernatur distinctio at non amet fugit enim. Maxime cupiditate voluptate inventore nam sed sunt iusto? Excepturi nostrum sapiente, consequuntur alias delectus, expedita ea quaerat rerum, enim eius libero ipsam?</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio tenetur officia placeat cupiditate saepe iusto deserunt, temporibus sequi iure quidem molestiae modi voluptate quae magnam ab sapiente doloribus ex laudantium expedita voluptas excepturi et corrupti id. Deserunt inventore reprehenderit est debitis distinctio. Tempora vitae quibusdam eius! Sunt laborum, deserunt laboriosam rem, eligendi libero dignissimos officia saepe ut nostrum illum soluta, inventore cum. Accusamus deleniti aliquam, provident expedita corporis quos minus dolorum aspernatur distinctio at non amet fugit enim. Maxime cupiditate voluptate inventore nam sed sunt iusto? Excepturi nostrum sapiente, consequuntur alias delectus, expedita ea quaerat rerum, enim eius libero ipsam?</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio tenetur officia placeat cupiditate saepe iusto deserunt, temporibus sequi iure quidem molestiae modi voluptate quae magnam ab sapiente doloribus ex laudantium expedita voluptas excepturi et corrupti id. Deserunt inventore reprehenderit est debitis distinctio. Tempora vitae quibusdam eius! Sunt laborum, deserunt laboriosam rem, eligendi libero dignissimos officia saepe ut nostrum illum soluta, inventore cum. Accusamus deleniti aliquam, provident expedita corporis quos minus dolorum aspernatur distinctio at non amet fugit enim. Maxime cupiditate voluptate inventore nam sed sunt iusto? Excepturi nostrum sapiente, consequuntur alias delectus, expedita ea quaerat rerum, enim eius libero ipsam?</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio tenetur officia placeat cupiditate saepe iusto deserunt, temporibus sequi iure quidem molestiae modi voluptate quae magnam ab sapiente doloribus ex laudantium expedita voluptas excepturi et corrupti id. Deserunt inventore reprehenderit est debitis distinctio. Tempora vitae quibusdam eius! Sunt laborum, deserunt laboriosam rem, eligendi libero dignissimos officia saepe ut nostrum illum soluta, inventore cum. Accusamus deleniti aliquam, provident expedita corporis quos minus dolorum aspernatur distinctio at non amet fugit enim. Maxime cupiditate voluptate inventore nam sed sunt iusto? Excepturi nostrum sapiente, consequuntur alias delectus, expedita ea quaerat rerum, enim eius libero ipsam?</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio tenetur officia placeat cupiditate saepe iusto deserunt, temporibus sequi iure quidem molestiae modi voluptate quae magnam ab sapiente doloribus ex laudantium expedita voluptas excepturi et corrupti id. Deserunt inventore reprehenderit est debitis distinctio. Tempora vitae quibusdam eius! Sunt laborum, deserunt laboriosam rem, eligendi libero dignissimos officia saepe ut nostrum illum soluta, inventore cum. Accusamus deleniti aliquam, provident expedita corporis quos minus dolorum aspernatur distinctio at non amet fugit enim. Maxime cupiditate voluptate inventore nam sed sunt iusto? Excepturi nostrum sapiente, consequuntur alias delectus, expedita ea quaerat rerum, enim eius libero ipsam?</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio tenetur officia placeat cupiditate saepe iusto deserunt, temporibus sequi iure quidem molestiae modi voluptate quae magnam ab sapiente doloribus ex laudantium expedita voluptas excepturi et corrupti id. Deserunt inventore reprehenderit est debitis distinctio. Tempora vitae quibusdam eius! Sunt laborum, deserunt laboriosam rem, eligendi libero dignissimos officia saepe ut nostrum illum soluta, inventore cum. Accusamus deleniti aliquam, provident expedita corporis quos minus dolorum aspernatur distinctio at non amet fugit enim. Maxime cupiditate voluptate inventore nam sed sunt iusto? Excepturi nostrum sapiente, consequuntur alias delectus, expedita ea quaerat rerum, enim eius libero ipsam?</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio tenetur officia placeat cupiditate saepe iusto deserunt, temporibus sequi iure quidem molestiae modi voluptate quae magnam ab sapiente doloribus ex laudantium expedita voluptas excepturi et corrupti id. Deserunt inventore reprehenderit est debitis distinctio. Tempora vitae quibusdam eius! Sunt laborum, deserunt laboriosam rem, eligendi libero dignissimos officia saepe ut nostrum illum soluta, inventore cum. Accusamus deleniti aliquam, provident expedita corporis quos minus dolorum aspernatur distinctio at non amet fugit enim. Maxime cupiditate voluptate inventore nam sed sunt iusto? Excepturi nostrum sapiente, consequuntur alias delectus, expedita ea quaerat rerum, enim eius libero ipsam?</p>
            </div>
            {/* <div className='min-h-screen'>jashdhj</div> */}
        </div>
    )
}

export default StickyDemo
